### ISSUE TITLE
add Wiki model

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#10]
a simple model, which will contain wiki pages to use as a reference (similar to Wiki in MS Teams channels)

id
page_id: integer 
title: string
body: text
version: integer

consider to use paper_trail gem, change the fields accordingly if needed.

please, implement the following functionality:
1) any edition of such page will create a new record in the DB, so anytime admin can browse through previous versions (found by page_id even when title is changed).
2) it can work with Markdown formatting
3) admins should be able to create, edit and browse through history, not admins only see the latest version

**Comment by yzadvirnyy** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
merged
