### ISSUE TITLE
Coordinator View // aka what to do page

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#11]
After a login, an admin user (aka coordinator) should see the page with the users/places, where he/she is linked as a coordinator.

[ People to pay attn | Places to pay attn ]

**Comment by ghost** [comment]
In progress

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/100867355/156924119-1828c6a2-787b-45e9-bbc3-9b4dce0f60c3.png)

**Comment by ghost** [comment]
Currently I filter users and places by signed in coordinator_id. Should I also filter out accommodation that has status `booked` or `not available`?
