### ISSUE TITLE
Create a user model 

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#3]
according to usual devise template

**Comment by vova** [comment]
**model User** 
id
name:string
email:string 
password: string
salt: string
status: integer
is_admin: boolean
coordinator_id: integer
from: string
destination: string
adults: integer
kids: integer
kids_comment: string
pets: boolean
phone: string
phone2: string
geo: string
accommodation_pref: integer 
transport_id: integer 
date_arrival: datetime
request_id: string
vaccination: boolean
comment: text
created_at
updated_at


The coordinator_id field is a link to another user with admin permissions.
This field should be updated with any record updates by any admin user.

**Comment by ghost** [comment]
In progress
