### ISSUE TITLE
Create Places Model 

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#4]
with the following fields:

name: string
type: integer
city: string
region: string
rooms_available: integer
beds: integer
kids_beds: integer
is_pets_allowed: boolean
capacity: integer (default: 2)
additional_child_place: integer (default: 0)
coordinator: integer
status: integer
price_per_day: integer
price_per_month: integer
is_price_in_dollars: boolean
address: string
distance_from_center: integer
available_since: datetime
available_till: datetime
phone: string
phone2: string 
is_realtor: boolean
contact_name: string
geo: string
website: string
created_at
updated_at

**Comment by ChernikovVolodymyr** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
Done
