### ISSUE TITLE
Make quick filters for the User list page

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#54]
Make quick filters for the User page: links which allow to filter users by their status in the top of the page:
Urgent to call | Accommodated. | In Office | In Trip | At Home | No Response | Declined

In the bottom of the page, add the line with the stats, so the amount of the users with those statuses, shown, like:

Urgent to call: 9 | Accommodated: 100 | In Office: 170 | In Trip: 5 | At Home: 8 | No Response: 9 | Declined: 10

add the necessary indexed to the DB

**Comment by ChernikovVolodymyr** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
in review

**Comment by ChernikovVolodymyr** [comment]
merged
