### ISSUE TITLE
Make quick filters for the Places list page

### ISSUE THREAD

**Issue by vova** [vova/war_shelter#57]
Make Quick filters for the places list page by their location, like:

Lviv | Ternopil | Chernivtsi | Ivano-Frankivsk | Uzhorod | Others 
(The last filter should show all the records, except places in Lviv | Ternopil | Chernivtsi | Ivano-Frankivsk | Uzhorod

and another line of filter by accommodation types:
Hotel | Hostel | Shelter | ..... (list all the types)

**Comment by ChernikovVolodymyr** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
merged
