### ISSUE TITLE
Add distance_from_center to User model

### ISSUE THREAD

**Issue by oleksandr-kychun** [vova/war_shelter#81]
We need to have a way to connect places in whole region. By default should be 100km

**Comment by oleksandr-kychun** [comment]
It seems that in order for this to work, we will need to create regions as a separate model or an enum field to match regions properly and assume that "center" is a location of Regional Center. Ex. for Lviv region we would have "center" as Lviv city. So we would match places and users with same region where place's distance from center cover the one in users model.

**Comment by ChernikovVolodymyr** [comment]
in progress

**Comment by ChernikovVolodymyr** [comment]
merged
